controller_manager:
  ros__parameters:
    update_rate: 1000

    gravity_compensation_controller:
      type: dynaarm_controllers/GravityCompensationController

    position_controller:
      type: forward_command_controller/ForwardCommandController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    dynaarm_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    effort_controller:
      type: effort_controllers/JointGroupEffortController

dynaarm_controller:
  ros__parameters:
    joints:    
      - SH_ROT
      - SH_FLE
      - EL_FLE
      - FA_ROT 
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: true

position_controller:
  ros__parameters:
    joints:
      - SH_ROT
      - SH_FLE
      - EL_FLE
      - FA_ROT      
    interface_name: position      

effort_controller:
  ros__parameters:
    joints:
      - SH_ROT
      - SH_FLE
      - EL_FLE
      - FA_ROT 

gravity_compensation_controller:
  ros__parameters:
    joints:
      - SH_ROT
      - SH_FLE
      - EL_FLE
      - FA_ROT           
    command_interfaces:
      - position   
      - velocity  
      - effort       
    state_interfaces:
      - position
      - velocity
      - effort
    gains:      
      SH_ROT: {p: 0.0, i: 0.0, d: 0.0}
      SH_FLE: {p: 0.0, i: 0.0, d: 0.0}
      EL_FLE: {p: 0.0, i: 0.0, d: 0.0}
      FA_ROT: {p: 0.0, i: 0.0, d: 0.0}
