controller_manager:
  ros__parameters:
    update_rate: 1000

    dynaarm_status_controller:
      type: dynaarm_controllers/StatusController

    gravity_compensation_controller:
      type: dynaarm_controllers/GravityCompensationController

    position_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    effort_controller:
      type: effort_controllers/JointGroupEffortController

dynaarm_status_controller:
  ros__parameters:
    joints:
      - SH_ROT
      - SH_FLE
      - EL_FLE
      - FA_ROT
      - WRIST_1
      - WRIST_2    

joint_trajectory_controller:
  ros__parameters:
    joints:
      - SH_ROT
      - SH_FLE
      - EL_FLE
      - FA_ROT
      - WRIST_1
      - WRIST_2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity    

position_controller:
  ros__parameters:
    joints:
      - SH_ROT
      - SH_FLE
      - EL_FLE
      - FA_ROT
      - WRIST_1
      - WRIST_2
    interface_name: position

effort_controller:
  ros__parameters:
    joints:
      - SH_ROT
      - SH_FLE
      - EL_FLE
      - FA_ROT
      - WRIST_1
      - WRIST_2

gravity_compensation_controller:
  ros__parameters:
    joints:
      - SH_ROT
      - SH_FLE
      - EL_FLE
      - FA_ROT
      - WRIST_1
      - WRIST_2
    command_interfaces:
      - position
      - velocity
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    gains:
      SH_ROT: {p: 100.0, i: 0.0, d: 15.0}
      SH_FLE: {p: 100.0, i: 0.0, d: 15.0}
      EL_FLE: {p: 100.0, i: 0.0, d: 15.0}
      FA_ROT: {p: 50.0, i: 0.0, d: 15.0}
      WRIST_1: {p: 50.0, i: 0.0, d: 15.0}
      WRIST_2: {p: 50.0, i: 0.0, d: 15.0}
